paths:
  xmidi_url: "https://drive.google.com/uc?id=1qDkSH31x7jN8X-2RyzB9wuxGji4QxYyA"
  xmidi_data_dir: "data/XMIDI_Dataset"
  xmidi_subset_dir: "data/XMIDI_subset"
  xmidi_generated_dir: "data/XMIDI_generated_music"
  xmidi_organized_dir: "data/XMIDI_Organized"
  generated_dir: "data/generated"
  prompts_dir: "data/prompts"
  prompts_json: "data/prompts/all_prompts.json"
  results_dir: "results"
  logs_dir: "src/logs"

models:
  midillm:
    script: "external/midi-llm/generate_transformers.py"
    python: "/home/arion/miniconda3/envs/midi-llm/bin/python"
    output_dir: "data/generated/midi-llm"

  clamp3:
    python: "C:/Users/oskar/.conda/envs/clamp3/python.exe"
    script: "external/clamp3/clamp3_score.py"
    env_dir: "C:/Users/oskar/.conda/envs/clamp3"

  musecoco:
    python: "/home/arion/miniconda3/envs/MuseCoco-tmp/bin/python"
    output_dir: "data/generated/musecoco"
    midi_subpath: "topk15-t0.7-ngram16/0/midi"
wandb:
  project: "wimu-music-eval"
  entity: null  # ustaw na nazwę swojego zespołu/użytkownika W&B
